const PRIMARY = '#330033';
const PRIMARY_LIGHT = '#8a4189';
const PRIMARY_DARK = '#280028';
const SECONDARY = '#ce7332';
const SECONDARY_LIGHT = '#766b7c';
const SECONDARY_DARK = '#403944';
const BACKGROUND = '#3c003f';
const READY = '#e3a3ff';
const WHITE = '#FFFFFF';
const OFF_WHITE = '#CCCCCC';
const BLACK = '#000000';

const COLORS = {
  PRIMARY,
  PRIMARY_LIGHT,
  PRIMARY_DARK,
  SECONDARY,
  SECONDARY_LIGHT,
  SECONDARY_DARK,
  BACKGROUND,
  BLACK,
  READY,
  WHITE,
  OFF_WHITE,
};

export default COLORS;
