const PRIMARY = '#7B1FA2';
const PRIMARY_LIGHT = '#ae52d4';
const PRIMARY_DARK = '#4a0072';
const SECONDARY = '#FFA000';
const SECONDARY_LIGHT = '#ffd149';
const SECONDARY_DARK = '#c67100';
const BACKGROUND = '#26252c';
const WHITE = '#FFFFFF';
const BLACK = '#000000';

const COLORS = {
  PRIMARY,
  PRIMARY_LIGHT,
  PRIMARY_DARK,
  SECONDARY,
  SECONDARY_LIGHT,
  SECONDARY_DARK,
  BACKGROUND,
  BLACK,
  WHITE,
};

export default COLORS;
