export const SET_IS_HOST = 'SET_IS_HOST';
export const ADD_SUGGESTIONS = 'ADD_SUGGESTIONS';
export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_WINNING_VOTE = 'SET_WINNING_VOTE';
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const RESET_ROOM = 'RESET_ROOM';
